name: rkmathi-stern
version: git
summary: summary.
description: |
  desccription.
confinement: devmode
base: core18
parts:
  rkmathi-stern:
    plugin: go
    go-importpath: github.com/rkmathi/stern
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  rkmathi-stern:
    command: bin/rkmathi-stern
